# 46. 에러 처리

`try-catch`문 사용시 프로그램 **강제 종료 없이도 코드 실행이 가능.** 에러 발생 없이도 **null 반환**, **단축 평가** 및 **옵셔널 체이닝 연산자**를 통해서도 **에러 방지가 가능**하다. 

### ∙ `try…catch…finally`

에러 발생시 **에러 처리 코드로 점프**하는 방식. `finally`는 생략 가능. `try` 코드 블록에서 에러 발생시 `**catch`문 변수가 생성되어 `catch` 코드 블록에서 유효.** 프로그램 강제 종료 방지가 가능. 

### ∙ `new Error()`

**에러를 상세히 설명하는 에러 메시지를 인수로 전달** 가능하며, 여러 객체를 생성한다. message, stack 프로퍼티를 지닌다. 

### ∙ `throw 문`

여러 객체 생성과 에러 발생은 다르다. `**try` 블록 내에서 `throw` 문으로 에러 객체를 던지면** `**catch` 문에 에러 변수 생성 및 에러 객체가 할당**되어 `**catch` 블록이 실행**된다.

```jsx
try {
	**throw** new Error('Error!');
} catch(e) {
	console.log(e);
}
```

### ∙ 에러 처리 주의사항

⑴ 에러는 호출자 방향(실행 컨텍스트 푸시 이전에 푸시된 컨텍스트 방향)으로 전파되어 **전역에서 캐치된다.** throw된 에러를 캐치해야 프로그램 강제 종료를 방지할 수 있다. 

⑵ 비동기 함수(`setTimeout`, 프로미스)의 **콜백 함수는 호출자가 부재하여 부가적으로 호출자를 생성**해야 하는데, 이를 `**async`/`await`으로 보완** 가능하다.